# Generated by Django 5.0.1 on 2024-01-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240111_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
    ]
